### ISSUE TITLE
name `SCALERS` is not defined

### ISSUE THREAD

**Issue by erfmah** [asarigun/mma#1]
Hi, in layers.py file you are using SCALERS, while it is not defined before using it. Would you please help me to figure out how to run that?

**Comment by asarigun** [comment]
Hello @erfmah,

Thank you so much for being interested in the repo and reporting the issue on GitHub. I have reviewed the details and identified that the problem occurred due to a missing import of `SCALERS` from `scalers.py`. I updated the code with the necessary imports. I appreciate you bringing this to my attention!

If you need any more help, please don't hesitate to let me know.

Best regards,
Ahmet
